import { StyleSheet } from 'react-native'

export const localAiStyles = StyleSheet.create({
  modelCard: {
    gap: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#393521',
    borderRadius: 18,
    backgroundColor: '#19170e',
  },
  modelHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  modelIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#ffd400',
  },
  modelIconText: { color: '#171400', fontSize: 20, fontWeight: '900' },
  modelCopy: { flex: 1, gap: 3 },
  eyebrow: { color: '#ffd400', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  modelTitle: { color: '#f3f4f6', fontSize: 16, fontWeight: '800' },
  modelDescription: { color: '#a6a7ab', fontSize: 12, lineHeight: 18 },
  progressTrack: {
    height: 7,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: '#333018',
  },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: '#ffd400' },
  progressLabel: { color: '#d8d4b6', fontSize: 12, fontWeight: '700' },
  actions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  primaryAction: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#ffd400',
  },
  primaryActionText: { color: '#171400', fontSize: 13, fontWeight: '900' },
  secondaryAction: {
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: '#4b4d54',
    borderRadius: 12,
  },
  secondaryActionText: { color: '#d2d4d8', fontSize: 12, fontWeight: '800' },
  readyRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  readyDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#70d68c' },
  readyText: { flex: 1, color: '#bfe9ca', fontSize: 12, fontWeight: '800' },
  error: { color: '#ff8f87', fontSize: 12 },
  assistantTrigger: {
    position: 'absolute',
    zIndex: 3,
    top: 2,
    right: 2,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 21,
    borderWidth: 1,
    borderColor: '#6d5f13',
    backgroundColor: '#2b260d',
  },
  assistantTriggerReady: { backgroundColor: '#ffd400', borderColor: '#ffd400' },
  assistantTriggerText: { color: '#f4dd58', fontSize: 19, fontWeight: '900' },
  assistantTriggerTextReady: { color: '#171400' },
  assistantOverlay: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    paddingTop: 66,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(0,0,0,.48)',
  },
  assistantPanel: {
    width: '88%',
    maxWidth: 340,
    gap: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#4a431b',
    borderRadius: 20,
    backgroundColor: '#17181c',
  },
  assistantHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  assistantOrb: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#ffd400',
  },
  assistantOrbListening: { backgroundColor: '#ff766f' },
  assistantOrbText: { color: '#171400', fontSize: 17, fontWeight: '900' },
  assistantHeaderCopy: { flex: 1, gap: 2 },
  assistantTitle: { color: '#f3f4f6', fontSize: 16, fontWeight: '900' },
  assistantStatus: { color: '#9aa0a8', fontSize: 11 },
  closeText: { color: '#aeb1b7', fontSize: 22, lineHeight: 24 },
  transcript: {
    minHeight: 52,
    padding: 11,
    color: '#e6e7e9',
    fontSize: 13,
    lineHeight: 18,
    borderRadius: 12,
    backgroundColor: '#22242a',
  },
  assistantHint: { color: '#9aa0a8', fontSize: 11, lineHeight: 16 },
  listenButton: {
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#ffd400',
  },
  listenButtonActive: { backgroundColor: '#ff766f' },
  listenButtonDisabled: { opacity: 0.5 },
  listenButtonText: { color: '#171400', fontSize: 13, fontWeight: '900' },
  result: { color: '#bfe9ca', fontSize: 12, lineHeight: 17 },
  assistantError: { color: '#ff9a93', fontSize: 12, lineHeight: 17 },
})
