import { StyleSheet } from 'react-native'

export const bracketStyles = StyleSheet.create({
  screen: { gap: 16, paddingBottom: 24 },
  header: {
    backgroundColor: '#17181c',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 20,
    padding: 18,
    gap: 14,
  },
  eyebrow: {
    color: '#ffd400',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  heading: { color: '#f3f4f6', fontSize: 24, fontWeight: '900' },
  championBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#2a260c',
    borderColor: '#ffd400',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  championIcon: { color: '#ffd400', fontSize: 24 },
  championLabel: {
    color: '#c8a900',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  championName: { color: '#fff6b3', fontSize: 15, fontWeight: '900' },
  empty: {
    minHeight: 300,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 28,
    backgroundColor: '#17181c',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 20,
  },
  emptyIcon: { color: '#ffd400', fontSize: 42, fontWeight: '300' },
  centeredHint: {
    maxWidth: 420,
    color: '#9aa0a8',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  nextMatch: {
    backgroundColor: '#24220d',
    borderColor: '#746200',
    borderWidth: 1,
    borderRadius: 16,
    padding: 15,
    gap: 4,
  },
  nextMatchLabel: {
    color: '#c8a900',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  nextMatchTitle: { color: '#fff6b3', fontSize: 18, fontWeight: '900' },
  nextMatchOpponent: { color: '#f3f4f6', fontSize: 14, fontWeight: '700' },
  bracket: {
    minHeight: 520,
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 12,
  },
  round: {
    width: 252,
    gap: 12,
  },
  roundHeader: {
    borderBottomColor: '#30333a',
    borderBottomWidth: 1,
    paddingBottom: 9,
  },
  roundNumber: {
    color: '#ffd400',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  roundTitle: { color: '#f3f4f6', fontSize: 17, fontWeight: '900' },
  matchStack: {
    flex: 1,
    justifyContent: 'space-around',
    gap: 14,
  },
  match: {
    backgroundColor: '#17181c',
    borderColor: '#30333a',
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 7,
  },
  matchMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 18,
  },
  matchLabel: {
    color: '#777c85',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  byeBadge: {
    color: '#171400',
    backgroundColor: '#ffd400',
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    fontSize: 9,
    fontWeight: '900',
  },
  participant: {
    minHeight: 43,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 11,
    paddingRight: 6,
    borderRadius: 9,
    backgroundColor: '#212329',
    borderColor: 'transparent',
    borderWidth: 1,
  },
  participantWinner: {
    backgroundColor: '#29270f',
    borderColor: '#8c7900',
  },
  participantMine: { borderColor: '#ffd400', borderWidth: 1.5 },
  participantName: {
    flex: 1,
    color: '#f3f4f6',
    fontSize: 13,
    fontWeight: '800',
  },
  participantPending: {
    color: '#747983',
    fontStyle: 'italic',
    fontWeight: '600',
  },
  score: {
    width: 42,
    height: 34,
    padding: 0,
    textAlign: 'center',
    color: '#f3f4f6',
    fontSize: 16,
    fontWeight: '900',
    backgroundColor: '#111216',
    borderColor: '#3b3e46',
    borderWidth: 1,
    borderRadius: 8,
  },
  readonlyScore: {
    minWidth: 30,
    color: '#f3f4f6',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  saveButton: {
    alignItems: 'center',
    paddingVertical: 7,
  },
  saveButtonText: {
    color: '#ffd400',
    fontSize: 11,
    fontWeight: '900',
  },
  waiting: {
    color: '#777c85',
    fontSize: 10,
    textAlign: 'center',
    paddingVertical: 5,
  },
})
