import { StyleSheet } from 'react-native'

export const discoveryFilterStyles = StyleSheet.create({
  trigger: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderRadius: 22, backgroundColor: '#17181c' },
  triggerIcon: { fontSize: 21, fontWeight: '900' },
  count: { position: 'absolute', top: -4, right: -4, minWidth: 18, height: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 9 },
  countText: { fontSize: 10, fontWeight: '900' },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.64)' },
  backdrop: { ...StyleSheet.absoluteFillObject },
  sheet: { maxHeight: '86%', paddingTop: 8, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: '#17181c', borderTopWidth: 1, borderColor: '#363940' },
  handle: { alignSelf: 'center', width: 38, height: 4, marginBottom: 8, borderRadius: 999, backgroundColor: '#5b5f68' },
  header: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingHorizontal: 20, paddingBottom: 16 },
  headerCopy: { flex: 1, gap: 4 },
  title: { color: '#f3f4f6', fontSize: 20, fontWeight: '900' },
  hint: { color: '#9aa0a8', fontSize: 12, lineHeight: 17 },
  closeButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: '#292c32' },
  closeText: { color: '#f3f4f6', fontSize: 23, lineHeight: 26 },
  content: { gap: 12, paddingHorizontal: 20, paddingBottom: 30 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 2 },
  label: { color: '#9aa0a8', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  clear: { fontSize: 12, fontWeight: '900' },
  sportGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sportOption: { position: 'relative', width: '47.7%', minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderWidth: 1, borderColor: '#34373e', borderRadius: 16, backgroundColor: '#202228' },
  sportImageWrap: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 14 },
  sportImage: { width: 38, height: 38 },
  sportFallback: { fontSize: 20, fontWeight: '900' },
  sportName: { flex: 1, color: '#f3f4f6', fontSize: 12, fontWeight: '800', lineHeight: 16 },
  sportCheck: { position: 'absolute', top: 7, right: 7, width: 17, height: 17, alignItems: 'center', justifyContent: 'center', borderRadius: 9 },
  sportCheckText: { fontSize: 11, fontWeight: '900' },
  moreSports: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 13, borderWidth: 1, borderColor: '#34373e', borderRadius: 13, backgroundColor: '#202228' },
  moreSportsText: { fontSize: 13, fontWeight: '900' },
  moreSportsChevron: { fontSize: 16, fontWeight: '900' },
  regionHint: { marginTop: -6, color: '#9aa0a8', fontSize: 11, lineHeight: 16 },
  regionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  regionOption: { width: '48.8%', minHeight: 42, justifyContent: 'center', paddingHorizontal: 11, borderWidth: 1, borderColor: '#34373e', borderRadius: 12, backgroundColor: '#202228' },
  regionOptionWide: { width: '100%' },
  regionText: { color: '#d9dce1', fontSize: 11, fontWeight: '800' },
})
