import { StyleSheet } from 'react-native'

export const eventTabStyles = StyleSheet.create({
  tabs: {
    flexDirection: 'row',
    gap: 4,
    backgroundColor: '#30333a',
    borderRadius: 999,
    padding: 5,
    marginBottom: 14,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    borderRadius: 999,
  },
  tabActive: { backgroundColor: '#ffd400' },
  label: { color: '#9aa0a8', fontSize: 13, fontWeight: '800' },
  labelActive: { color: '#171400' },
})

export const eventCardStyles = StyleSheet.create({
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 2,
  },
  card: {
    width: '48%',
    minHeight: 300,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    backgroundColor: '#17181c',
  },
  cardPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  imagePlaceholder: {
    height: 122,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#29270f',
    borderBottomWidth: 1,
    borderBottomColor: '#665814',
  },
  sportImage: { width: 78, height: 78 },
  sportMark: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffd400',
  },
  sportMarkText: { color: '#171400', fontSize: 20, fontWeight: '900' },
  imageHint: {
    position: 'absolute',
    top: 10,
    left: 10,
    color: '#c8a900',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  imageSport: {
    position: 'absolute',
    bottom: 9,
    left: 10,
    color: '#fff6b3',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  body: { flex: 1, padding: 11, gap: 6 },
  type: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    backgroundColor: '#30333a',
    color: '#d9dce1',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  title: { color: '#f3f4f6', fontSize: 15, fontWeight: '900', lineHeight: 19 },
  description: { color: '#9aa0a8', fontSize: 11, lineHeight: 15 },
  meta: { marginTop: 'auto', gap: 3, paddingTop: 5 },
  metaText: { color: '#c4c8cf', fontSize: 10, fontWeight: '700' },
})
