import { StyleSheet } from 'react-native'

export const formStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: '#0b0c0e' },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    gap: 16,
    padding: 24,
    backgroundColor: '#f5f7fb',
  },
  onboardingContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
    gap: 14,
    backgroundColor: '#0b0c0e',
  },
  brand: {
    fontSize: 20,
    fontWeight: '800',
    color: '#f3f4f6',
    letterSpacing: 1,
  },
  accent: { color: '#ffd400' },
  card: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 18,
    gap: 16,
  },
  title: { fontSize: 32, fontWeight: '800', color: '#f3f4f6' },
  field: { gap: 7 },
  label: { color: '#f3f4f6', fontSize: 14, fontWeight: '700' },
  error: { color: '#ff8f87', fontSize: 13 },
  input: {
    backgroundColor: '#1d1f24',
    borderColor: '#2b2e34',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 13,
    color: '#f3f4f6',
    fontSize: 16,
  },
  dateButton: {
    backgroundColor: '#1d1f24',
    borderColor: '#2b2e34',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateValue: { color: '#f3f4f6', fontSize: 16 },
  datePlaceholder: { color: '#9aa0a8', fontSize: 16 },
  genderRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  genderChip: {
    borderWidth: 1.5,
    borderColor: '#2b2e34',
    backgroundColor: '#1d1f24',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  genderChipSelected: {
    backgroundColor: '#ffd400',
    borderColor: '#ffd400',
  },
  genderText: { color: '#f3f4f6', fontSize: 13, fontWeight: '700' },
  continueButton: {
    backgroundColor: '#ffd400',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 4,
  },
  continueText: { color: '#171400', fontSize: 16, fontWeight: '800' },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(0,0,0,.7)',
  },
  modalSheet: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '85%',
    backgroundColor: '#17181c',
    borderRadius: 24,
    borderColor: '#2b2e34',
    borderWidth: 1,
    padding: 20,
    gap: 10,
  },
  modalTitle: { color: '#f3f4f6', fontSize: 20, fontWeight: '800' },
  modalHint: { color: '#9aa0a8', fontSize: 13 },
  pickerLabel: {
    color: '#9aa0a8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 5,
  },
  optionRow: { gap: 8 },
  dateOption: {
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#1d1f24',
  },
  dateOptionSelected: { backgroundColor: '#ffd400', borderColor: '#ffd400' },
  dateOptionText: { color: '#f3f4f6', fontWeight: '700' },
  dateOptionTextSelected: { color: '#171400' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  monthOption: {
    width: '15%',
    alignItems: 'center',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 7,
    backgroundColor: '#1d1f24',
  },
  dayGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  dayOption: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#1d1f24',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 20,
    marginTop: 8,
  },
  cancelText: { color: '#f3f4f6', fontWeight: '700' },
  saveDateButton: {
    backgroundColor: '#ffd400',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  saveDateText: { color: '#171400', fontWeight: '800' },
  languages: {
    flexDirection: 'row',
    gap: 8,
    position: 'absolute',
    top: 60,
    right: 16,
  },
})
