import { StyleSheet } from 'react-native'

export const formStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: '#0b0c0e' },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    gap: 16,
    padding: 24,
    backgroundColor: '#f5f7fb',
  },
  onboardingContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
    gap: 14,
    backgroundColor: '#0b0c0e',
  },
  brand: {
    fontSize: 20,
    fontWeight: '800',
    color: '#f3f4f6',
    letterSpacing: 1,
  },
  accent: { color: '#ffd400' },
  card: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 18,
    gap: 16,
  },
  title: { fontSize: 32, fontWeight: '800', color: '#f3f4f6' },
  field: { gap: 7 },
  label: { color: '#f3f4f6', fontSize: 14, fontWeight: '700' },
  error: { color: '#ff8f87', fontSize: 13 },
  input: {
    backgroundColor: '#1d1f24',
    borderColor: '#2b2e34',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 13,
    color: '#f3f4f6',
    fontSize: 16,
  },
  dateButton: {
    backgroundColor: '#1d1f24',
    borderColor: '#2b2e34',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateValue: { color: '#f3f4f6', fontSize: 16 },
  datePlaceholder: { color: '#9aa0a8', fontSize: 16 },
  dateTimeControl: { flexDirection: 'row', overflow: 'hidden', borderWidth: 1.5, borderColor: '#2b2e34', borderRadius: 12, backgroundColor: '#1d1f24' },
  dateTimeDate: { flex: 1, justifyContent: 'center', paddingHorizontal: 13, paddingVertical: 13 },
  dateTimeInput: { width: 92, justifyContent: 'center', borderWidth: 0, borderLeftWidth: 1.5, borderLeftColor: '#2b2e34', borderRadius: 0, paddingHorizontal: 11, paddingVertical: 13, backgroundColor: 'transparent' },
  genderRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  compactChipRow: { flexWrap: 'nowrap', gap: 5 },
  eventFormColumns: { gap: 10 },
  eventFormColumn: { gap: 6 },
  genderChip: {
    borderWidth: 1.5,
    borderColor: '#2b2e34',
    backgroundColor: '#1d1f24',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  genderChipSelected: {
    backgroundColor: '#ffd400',
    borderColor: '#ffd400',
  },
  compactChip: { flex: 1, alignItems: 'center', paddingHorizontal: 5, paddingVertical: 8 },
  genderText: { color: '#f3f4f6', fontSize: 13, fontWeight: '700' },
  compactChipText: { fontSize: 11 },
  genderTextSelected: { color: '#171400' },
  continueButton: {
    backgroundColor: '#ffd400',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 4,
  },
  continueText: { color: '#171400', fontSize: 16, fontWeight: '800' },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(0,0,0,.7)',
  },
  modalSheet: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '85%',
    backgroundColor: '#17181c',
    borderRadius: 24,
    borderColor: '#2b2e34',
    borderWidth: 1,
    padding: 20,
    gap: 10,
  },
  eventModalOverlay: {
    justifyContent: 'flex-start',
    paddingVertical: 28,
  },
  eventModalBackdrop: { ...StyleSheet.absoluteFillObject },
  eventModalSafeArea: { flex: 1 },
  eventModalSheet: {
    flex: 1,
    width: '100%',
    maxWidth: 520,
    maxHeight: '94%',
    backgroundColor: '#17181c',
    borderRadius: 24,
    borderColor: '#2b2e34',
    borderWidth: 1,
    padding: 12,
  },
  eventModalScroll: { flex: 1 },
  eventModalScrollContent: { flexGrow: 1, paddingBottom: 28 },
  modalEventForm: {
    gap: 12,
    padding: 6,
    paddingBottom: 6,
  },
  modalEventTitle: { marginRight: 42 },
  eventModalClose: {
    position: 'absolute',
    zIndex: 1,
    top: 8,
    right: 12,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#30333a',
  },
  eventModalCloseText: { color: '#f3f4f6', fontSize: 21, lineHeight: 24 },
  eventSectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  eventSectionCopy: { flex: 1, gap: 2 },
  eventFormSection: { gap: 10, padding: 12, borderWidth: 1, borderColor: '#2b2e34', borderRadius: 16, backgroundColor: '#111216' },
  eventSectionLabel: { color: '#ffd400', fontSize: 11, fontWeight: '900', letterSpacing: 1 },
  eventCategoryCard: {
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#343841',
    backgroundColor: '#111216',
  },
  eventRemoveText: { color: '#ff8f87', fontSize: 13, fontWeight: '700' },
  eventNumberRow: { flexDirection: 'row', gap: 10 },
  eventNumberField: { flex: 1, gap: 5 },
  sportPicker: { gap: 8 },
  sportGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sportOption: { width: '48%', minHeight: 72, alignItems: 'center', justifyContent: 'center', gap: 4, padding: 8, borderWidth: 1.5, borderColor: '#2b2e34', borderRadius: 12, backgroundColor: '#1d1f24' },
  sportOptionSelected: { borderColor: '#ffd400', backgroundColor: '#ffd400' },
  sportOptionEmoji: { fontSize: 32 },
  sportOptionText: { color: '#f3f4f6', fontSize: 12, fontWeight: '800' },
  sportOptionTextSelected: { color: '#171400' },
  expandSportsButton: { alignItems: 'center', paddingVertical: 7 },
  expandSportsText: { fontSize: 13, fontWeight: '800' },
  regionSelect: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1.5, borderColor: '#2b2e34', borderRadius: 12, padding: 13, backgroundColor: '#1d1f24' },
  regionChevron: { color: '#9aa0a8', fontSize: 16, fontWeight: '800' },
  regionOptions: { gap: 6, padding: 8, borderWidth: 1, borderColor: '#343841', borderRadius: 12, backgroundColor: '#111216' },
  regionOption: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 9 },
  regionOptionSelected: { backgroundColor: '#ffd400' },
  regionOptionText: { color: '#f3f4f6', fontSize: 14, fontWeight: '700' },
  categoryCardHeader: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingVertical: 3 },
  categoryCardCopy: { flex: 1, gap: 2 },
  categoryAction: { fontSize: 12, fontWeight: '800' },
  categorySummary: { flex: 1, color: '#9aa0a8', fontSize: 12 },
  addCategoryButton: { borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 },
  addCategoryText: { fontSize: 12, fontWeight: '800' },
  nameCoverRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  nameField: { flex: 1, gap: 6 },
  coverPickerButton: { width: 76, height: 70, alignItems: 'center', justifyContent: 'center', gap: 4, overflow: 'hidden', borderRadius: 12, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#555a65', backgroundColor: '#1d1f24' },
  coverPreview: { ...StyleSheet.absoluteFillObject, opacity: 0.72 },
  coverPickerEmoji: { fontSize: 24 },
  coverPickerTitle: { color: '#f3f4f6', fontSize: 10, fontWeight: '800', textAlign: 'center', paddingHorizontal: 4 },
  modalTitle: { color: '#f3f4f6', fontSize: 20, fontWeight: '800' },
  modalHint: { color: '#9aa0a8', fontSize: 13 },
  pickerLabel: {
    color: '#9aa0a8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 5,
  },
  optionRow: { gap: 8 },
  dateOption: {
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#1d1f24',
  },
  dateOptionSelected: { backgroundColor: '#ffd400', borderColor: '#ffd400' },
  dateOptionText: { color: '#f3f4f6', fontWeight: '700' },
  dateOptionTextSelected: { color: '#171400' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  monthOption: {
    width: '15%',
    alignItems: 'center',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 7,
    backgroundColor: '#1d1f24',
  },
  dayGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  dayOption: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#2b2e34',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#1d1f24',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 20,
    marginTop: 8,
  },
  cancelText: { color: '#f3f4f6', fontWeight: '700' },
  saveDateButton: {
    backgroundColor: '#ffd400',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  saveDateText: { color: '#171400', fontWeight: '800' },
  languages: {
    flexDirection: 'row',
    gap: 8,
    position: 'absolute',
    top: 60,
    right: 16,
  },
})
