import { StyleSheet } from 'react-native'

export const mainStyles = StyleSheet.create({
  mainApp: { flex: 1, backgroundColor: '#0b0c0e' },
  mainHeader: {
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0b0c0e',
  },
  headerBrand: { color: '#f3f4f6', fontSize: 17, fontWeight: '800' },
  headerTitle: {
    color: '#f3f4f6',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 3,
  },
  mainContent: { paddingHorizontal: 20, paddingBottom: 108, gap: 12 },
  mainCard: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 16,
    gap: 7,
  },
  heroCard: {
    backgroundColor: '#25220f',
    borderColor: '#665814',
    paddingVertical: 22,
  },
  cardKicker: { color: '#ffd400', fontSize: 11, fontWeight: '800' },
  homeGreeting: { color: '#f3f4f6', fontSize: 25, fontWeight: '800' },
  mainMuted: { color: '#9aa0a8', fontSize: 14, lineHeight: 20 },
  sectionTitle: {
    color: '#9aa0a8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 10,
  },
  cardTitle: { color: '#f3f4f6', fontSize: 16, fontWeight: '700' },
  emptyState: {
    flex: 1,
    minHeight: 300,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    padding: 30,
  },
  emptyIcon: { color: '#ffd400', fontSize: 54 },
  emptyTitle: { color: '#f3f4f6', fontSize: 24, fontWeight: '800' },
  profileCard: { alignItems: 'center', paddingVertical: 24, gap: 7 },
  avatar: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffd400',
  },
  avatarText: { color: '#171400', fontSize: 30, fontWeight: '800' },
  profileName: { color: '#f3f4f6', fontSize: 22, fontWeight: '800' },
  signOutButton: {
    borderWidth: 1,
    borderColor: '#5c3431',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  signOutText: { color: '#ff8f87', fontWeight: '800' },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 14,
    height: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#1a1c21',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 34,
  },
  tabItem: { width: 70, alignItems: 'center', gap: 2 },
  tabIcon: {
    width: 38,
    height: 38,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#30333a',
  },
  tabIconActive: {
    width: 38,
    height: 38,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#ffd400',
  },
  tabIconText: { color: '#7d818a', fontSize: 20 },
  tabIconTextActive: { color: '#171400' },
  tabLabel: { color: '#7d818a', fontSize: 10, fontWeight: '700' },
  tabLabelActive: { color: '#ffd400' },
})
