import { StyleSheet } from 'react-native'

export const matchResultStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheet: {
    height: '94%',
    maxHeight: '94%',
    backgroundColor: '#111216',
    borderTopColor: '#3a3d44',
    borderTopWidth: 1,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingTop: 9,
    zIndex: 1,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    marginBottom: 12,
    borderRadius: 99,
    backgroundColor: '#4a4d55',
  },
  scrollArea: { flex: 1 },
  content: { gap: 18, paddingHorizontal: 18, paddingBottom: 34 },
  header: { gap: 5, paddingRight: 38 },
  eyebrow: {
    color: '#ffd400',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.3,
  },
  title: { color: '#f5f6f7', fontSize: 24, fontWeight: '900' },
  subtitle: { color: '#8f949d', fontSize: 12, lineHeight: 18 },
  close: {
    position: 'absolute',
    zIndex: 2,
    top: 16,
    right: 16,
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: '#25272d',
  },
  closeText: { color: '#f5f6f7', fontSize: 23, lineHeight: 25 },
  scoreCard: {
    padding: 14,
    gap: 12,
    borderRadius: 18,
    borderColor: '#34373e',
    borderWidth: 1,
    backgroundColor: '#191a1f',
  },
  scoreRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  scoreSide: { flex: 1, alignItems: 'center', gap: 8 },
  teamName: {
    minHeight: 34,
    color: '#f5f6f7',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  scoreInput: {
    width: 72,
    height: 58,
    padding: 0,
    textAlign: 'center',
    color: '#f5f6f7',
    fontSize: 28,
    fontWeight: '900',
    borderRadius: 13,
    borderColor: '#555a64',
    borderWidth: 1,
    backgroundColor: '#0e0f12',
  },
  scoreTap: {
    width: 94,
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    borderColor: '#ffd400',
    borderWidth: 1.5,
    backgroundColor: '#29270f',
  },
  scoreValue: { color: '#fff7b3', fontSize: 34, fontWeight: '900' },
  scoreTapHint: { color: '#c8a900', fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
  scoreMinus: { paddingHorizontal: 8, paddingVertical: 4 },
  scoreMinusText: { color: '#8f949d', fontSize: 10, fontWeight: '700' },
  scoreDivider: { color: '#ffd400', fontSize: 26, fontWeight: '900' },
  section: { gap: 10 },
  sectionTitle: {
    color: '#f0f1f3',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  sectionHint: { color: '#858a93', fontSize: 11, lineHeight: 16 },
  metaRow: { flexDirection: 'row', gap: 10 },
  metaField: { flex: 1, gap: 6 },
  label: {
    color: '#aeb2b9',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  input: {
    height: 45,
    paddingHorizontal: 12,
    color: '#f5f6f7',
    fontSize: 14,
    fontWeight: '700',
    borderRadius: 11,
    borderColor: '#3a3d44',
    borderWidth: 1,
    backgroundColor: '#191a1f',
  },
  playerGroup: { gap: 7 },
  scorerToggle: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 12,
    borderColor: '#3b3e46',
    borderWidth: 1,
    backgroundColor: '#1b1d22',
  },
  scorerToggleCopy: { flex: 1, gap: 3, paddingRight: 12 },
  scorerToggleTitle: { color: '#f1f2f4', fontSize: 13, fontWeight: '900' },
  scorerToggleHint: { color: '#858a93', fontSize: 10, lineHeight: 14 },
  scorerToggleValue: { color: '#ffd400', fontSize: 11, fontWeight: '900' },
  scorerSummary: { color: '#858a93', fontSize: 10, marginTop: 3 },
  goalEntryTeamA: { borderLeftColor: '#69c8ee', borderLeftWidth: 3 },
  goalEntryTeamB: { borderLeftColor: '#c69bed', borderLeftWidth: 3 },
  scorerChevron: { color: '#ffd400', fontSize: 20, fontWeight: '900' },
  goalEntry: { overflow: 'hidden', borderRadius: 14, borderColor: '#3b3e46', borderWidth: 1, backgroundColor: '#1b1d22' },
  goalEntryHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, gap: 10 },
  goalNumber: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: '#302d12' },
  goalNumberTeamA: { backgroundColor: '#163240' },
  goalNumberTeamB: { backgroundColor: '#392240' },
  goalNumberText: { color: '#ffd400', fontSize: 14, fontWeight: '900' },
  goalEntryCopy: { flex: 1, gap: 3 },
  goalMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  goalEntryTitle: { color: '#f1f2f4', fontSize: 12, fontWeight: '800' },
  teamBadge: { maxWidth: '68%', paddingHorizontal: 7, paddingVertical: 2, borderRadius: 99 },
  teamBadgeA: { backgroundColor: '#163240' },
  teamBadgeB: { backgroundColor: '#392240' },
  teamBadgeText: { fontSize: 9, fontWeight: '900' },
  teamBadgeTextA: { color: '#9ce3ff' },
  teamBadgeTextB: { color: '#e5c3ff' },
  goalEntryPrompt: { color: '#ffd400', fontSize: 11, fontWeight: '800' },
  goalEntrySelected: { color: '#aeb2b9', fontSize: 11, fontWeight: '700' },
  rosterList: { borderTopColor: '#34373e', borderTopWidth: 1, padding: 10, gap: 8 },
  rosterPrompt: { color: '#8f949d', fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  rosterGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  rosterPlayer: { width: '48.5%', minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, borderRadius: 10, borderWidth: 1, borderColor: '#34373e', backgroundColor: '#202228' },
  rosterPlayerSelected: { borderColor: '#ffd400', backgroundColor: '#2b280c' },
  rosterSelectedMark: { color: '#ffd400', fontSize: 15, fontWeight: '900' },
  sideLabel: { color: '#ffd400', fontSize: 10, fontWeight: '900' },
  playerRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#1b1d22',
    borderColor: '#30333a',
    borderWidth: 1,
  },
  playerInfo: { flex: 1, gap: 2 },
  playerName: { color: '#f1f2f4', fontSize: 13, fontWeight: '800' },
  playerId: { color: '#777c85', fontSize: 9 },
  stepButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#30333a',
  },
  stepText: { color: '#f5f6f7', fontSize: 18, fontWeight: '900' },
  goalCount: {
    minWidth: 22,
    color: '#ffd400',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  mvpRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderColor: '#34373e',
    borderWidth: 1,
    backgroundColor: '#1b1d22',
  },
  mvpRowSelected: {
    borderColor: '#ffd400',
    backgroundColor: '#2b280c',
  },
  mvpToggle: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, borderRadius: 12, borderColor: '#34373e', borderWidth: 1, backgroundColor: '#1b1d22' },
  mvpToggleText: { color: '#f1f2f4', fontSize: 12, fontWeight: '800' },
  mvpToggleChevron: { color: '#ffd400', fontSize: 20, fontWeight: '900' },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderColor: '#686d76',
    borderWidth: 2,
  },
  radioSelected: { borderColor: '#ffd400', borderWidth: 5 },
  mvpName: { flex: 1, color: '#f1f2f4', fontSize: 13, fontWeight: '800' },
  clearMvp: { alignSelf: 'flex-start', paddingVertical: 5 },
  clearMvpText: { color: '#aeb2b9', fontSize: 11, fontWeight: '700' },
  error: {
    color: '#ff8d8d',
    padding: 11,
    borderRadius: 10,
    backgroundColor: '#351a1c',
    fontSize: 12,
    fontWeight: '700',
  },
  save: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#ffd400',
  },
  saveDisabled: { opacity: 0.55 },
  saveText: { color: '#171400', fontSize: 14, fontWeight: '900' },
})
