import { StyleSheet } from 'react-native'

export const teamStyles = StyleSheet.create({
  section: { gap: 10, marginTop: 10 },
  teamHub: { gap: 10, marginTop: 10 },
  teamHubHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  teamHubSubtitle: { color: '#9aa0a8', fontSize: 11, marginTop: 3 },
  teamHubCount: { minWidth: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 16 },
  teamHubCountText: { fontSize: 13, fontWeight: '900' },
  teamHubCard: { minHeight: 68, backgroundColor: '#17181c', borderWidth: 1, borderColor: '#2b2e34', borderRadius: 18, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 },
  teamHubArrow: { fontSize: 25, fontWeight: '700', lineHeight: 25 },
  teamAddButton: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 18, borderWidth: 1, borderStyle: 'dashed', padding: 12 },
  teamAddIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  teamAddIconText: { fontSize: 24, fontWeight: '500', lineHeight: 27 },
  teamAddTitle: { fontSize: 13, fontWeight: '900' },
  teamAddForm: { gap: 12, padding: 15, borderRadius: 18, borderWidth: 1, borderColor: '#2b2e34', backgroundColor: '#17181c' },
  card: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  badge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: '#101114', fontWeight: '900', fontSize: 16 },
  info: { flex: 1, gap: 3 },
  title: { color: '#f3f4f6', fontSize: 16, fontWeight: '800' },
  muted: { color: '#9aa0a8', fontSize: 13 },
  sectionTitle: {
    color: '#9aa0a8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  eventTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  qrButton: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 7 },
  qrButtonText: { fontSize: 12, fontWeight: '900' },
  qrOverlay: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: 'rgba(0,0,0,0.74)' },
  qrSheet: { gap: 14, alignItems: 'center', padding: 22, borderRadius: 22, backgroundColor: '#17181c', borderColor: '#3b3e46', borderWidth: 1 },
  qrTitle: { color: '#f3f4f6', fontSize: 22, fontWeight: '900' },
  qrSubtitle: { color: '#ffd400', fontSize: 13, fontWeight: '800', textAlign: 'center' },
  qrCodeWrap: { padding: 12, borderRadius: 14, backgroundColor: '#ffffff' },
  qrParticipant: { color: '#f3f4f6', fontSize: 16, fontWeight: '800' },
  scannerScreen: { flex: 1, gap: 16, padding: 20, backgroundColor: '#101114' },
  scannerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  scannerNotice: { gap: 16, padding: 20, borderRadius: 16, backgroundColor: '#17181c' },
  camera: { flex: 1, minHeight: 320, overflow: 'hidden', borderRadius: 22 },
  scannerHint: { color: '#f3f4f6', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  scannerResult: { gap: 12, padding: 20, borderRadius: 18, backgroundColor: '#17181c' },
  qrError: { color: '#ff9c96', textAlign: 'center', fontSize: 12, fontWeight: '700' },
  button: {
    borderColor: '#ffd400',
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  buttonText: { color: '#ffd400', fontWeight: '800' },
  form: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 15,
    gap: 12,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 18,
  },
  primary: {
    backgroundColor: '#ffd400',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  primaryText: { color: '#171400', fontWeight: '800' },
  cancel: { color: '#f3f4f6', fontWeight: '700' },
  back: { color: '#ffd400', fontWeight: '700', marginTop: 2 },
  hero: { alignItems: 'center', paddingVertical: 22 },
  member: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 14,
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  memberAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#30333a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberAvatarText: { color: '#f3f4f6', fontWeight: '800' },
})
