import { StyleSheet } from 'react-native'

export const teamStyles = StyleSheet.create({
  section: { gap: 10, marginTop: 10 },
  card: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  badge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: '#101114', fontWeight: '900', fontSize: 16 },
  info: { flex: 1, gap: 3 },
  title: { color: '#f3f4f6', fontSize: 16, fontWeight: '800' },
  muted: { color: '#9aa0a8', fontSize: 13 },
  sectionTitle: {
    color: '#9aa0a8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  button: {
    borderColor: '#ffd400',
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  buttonText: { color: '#ffd400', fontWeight: '800' },
  form: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 18,
    padding: 15,
    gap: 12,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 18,
  },
  primary: {
    backgroundColor: '#ffd400',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  primaryText: { color: '#171400', fontWeight: '800' },
  cancel: { color: '#f3f4f6', fontWeight: '700' },
  back: { color: '#ffd400', fontWeight: '700', marginTop: 2 },
  hero: { alignItems: 'center', paddingVertical: 22 },
  member: {
    backgroundColor: '#17181c',
    borderWidth: 1,
    borderColor: '#2b2e34',
    borderRadius: 14,
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  memberAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#30333a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberAvatarText: { color: '#f3f4f6', fontWeight: '800' },
})
