import { createContext, useContext, useEffect, useRef, useState } from 'react'
import { getStoredValue, removeStoredValue, setStoredValue } from './services/storage'
import { apiBaseUrl } from './config/env'
export type User = { id: string; display_name?: string; nickname?: string; preferred_language: 'sk' | 'en'; onboarding_completed: boolean }
type OnboardingData = { first_name: string; last_name: string; birth_date: string; gender: 'male' | 'female' | 'other' | 'prefer_not_to_say' }
type Auth = { user: User | null; loading: boolean; signIn: (credential: string) => Promise<void>; developmentSignIn: () => Promise<void>; signOut: () => Promise<void>; completeOnboarding: (data: OnboardingData) => Promise<void>; authenticatedFetch: (path: string, init?: RequestInit) => Promise<Response>; updateNickname: (nickname: string) => Promise<void> }
const C = createContext<Auth>({ user: null, loading: true, signIn: async () => {}, developmentSignIn: async () => {}, signOut: async () => {}, completeOnboarding: async () => {}, authenticatedFetch: async () => { throw Error('AUTH_REQUIRED') }, updateNickname: async () => {} })
const refreshKey = 'sport-refresh-token'
const userKey = 'sport-current-user'
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); const refreshInFlight = useRef<Promise<{ access_token: string; refresh_token: string; user: User }> | null>(null)
  const request = async (path: string, body: object) => fetch(`${apiBaseUrl}/api/v1/auth/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  const storeUser = async (nextUser: User) => { setUser(nextUser); await setStoredValue(userKey, JSON.stringify(nextUser)) }
  const refreshSession = async () => { if (refreshInFlight.current) return refreshInFlight.current; const pending = (async () => { const token = await getStoredValue(refreshKey); if (!token) throw Error('AUTH_REQUIRED'); const r = await request('refresh', { refresh_token: token }); if (!r.ok) { if (await getStoredValue(refreshKey) === token) { await removeStoredValue(refreshKey); await removeStoredValue(userKey); setUser(null) }; throw Error('AUTH_REQUIRED') }; const session = await r.json(); await setStoredValue(refreshKey, session.refresh_token); await storeUser(session.user); return session })(); refreshInFlight.current = pending; try { return await pending } finally { refreshInFlight.current = null } }
  useEffect(() => { const bootstrap = async () => { const [cached, token] = await Promise.all([getStoredValue(userKey), getStoredValue(refreshKey)]); if (cached && token) { try { setUser(JSON.parse(cached) as User); setLoading(false); void refreshSession().catch(() => undefined); return } catch { await removeStoredValue(userKey) } } if (token) await refreshSession().catch(() => undefined); setLoading(false) }; void bootstrap() }, [])
  const signIn = async (credential: string) => { const r = await request('google', { credential, platform: 'mobile' }); if (!r.ok) throw Error(); const d = await r.json(); await setStoredValue(refreshKey, d.refresh_token); await storeUser(d.user) }
  const developmentSignIn = async () => { const r = await request('development-login', {}); if (!r.ok) throw Error(); const d = await r.json(); await setStoredValue(refreshKey, d.refresh_token); await storeUser(d.user) }
  const completeOnboarding = async (data: OnboardingData) => { const session = await refreshSession(); const r = await fetch(`${apiBaseUrl}/api/v1/users/me/onboarding`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ ...data, preferred_language: user?.preferred_language ?? 'sk' }) }); if (!r.ok) throw Error('ONBOARDING_FAILED'); await storeUser(await r.json()) }
  const authenticatedFetch = async (path: string, init: RequestInit = {}) => { const session = await refreshSession(); return fetch(`${apiBaseUrl}/api/v1${path}`, { ...init, headers: { ...init.headers, Authorization: `Bearer ${session.access_token}` } }) }
  const updateNickname = async (nickname: string) => { const r = await authenticatedFetch('/users/me/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nickname }) }); if (!r.ok) throw Error('NICKNAME_FAILED'); await storeUser(await r.json()) }
  const signOut = async () => { const token = await getStoredValue(refreshKey); if (token) await request('logout', { refresh_token: token }); await removeStoredValue(refreshKey); await removeStoredValue(userKey); setUser(null) }
  return <C.Provider value={{ user, loading, signIn, developmentSignIn, signOut, completeOnboarding, authenticatedFetch, updateNickname }}>{children}</C.Provider> }
export const useAuth = () => useContext(C)
