import { createContext, useContext, useEffect, useState } from 'react'
import { getStoredValue, removeStoredValue, setStoredValue } from './services/storage'
import { apiBaseUrl } from './config/env'
export type User = { id: string; display_name?: string; preferred_language: 'sk' | 'en'; onboarding_completed: boolean }
type OnboardingData = { first_name: string; last_name: string; birth_date: string; gender: 'male' | 'female' | 'other' | 'prefer_not_to_say' }
type Auth = { user: User | null; loading: boolean; signIn: (credential: string) => Promise<void>; developmentSignIn: () => Promise<void>; signOut: () => Promise<void>; completeOnboarding: (data: OnboardingData) => Promise<void> }
const C = createContext<Auth>({ user: null, loading: true, signIn: async () => {}, developmentSignIn: async () => {}, signOut: async () => {}, completeOnboarding: async () => {} })
const refreshKey = 'sport-refresh-token'
const userKey = 'sport-current-user'
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true)
  const request = async (path: string, body: object) => fetch(`${apiBaseUrl}/api/v1/auth/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  const storeUser = async (nextUser: User) => { setUser(nextUser); await setStoredValue(userKey, JSON.stringify(nextUser)) }
  useEffect(() => { const refresh = async (token: string) => { const r = await request('refresh', { refresh_token: token }); if (!r.ok) { if (await getStoredValue(refreshKey) !== token) return; await removeStoredValue(refreshKey); await removeStoredValue(userKey); setUser(null); return }; const d = await r.json(); if (await getStoredValue(refreshKey) !== token) return; await setStoredValue(refreshKey, d.refresh_token); await storeUser(d.user) }; const bootstrap = async () => { const [cached, token] = await Promise.all([getStoredValue(userKey), getStoredValue(refreshKey)]); if (cached && token) { try { setUser(JSON.parse(cached) as User); setLoading(false); void refresh(token).catch(() => undefined); return } catch { await removeStoredValue(userKey) } } if (token) await refresh(token).catch(() => undefined); setLoading(false) }; void bootstrap() }, [])
  const signIn = async (credential: string) => { const r = await request('google', { credential, platform: 'mobile' }); if (!r.ok) throw Error(); const d = await r.json(); await setStoredValue(refreshKey, d.refresh_token); await storeUser(d.user) }
  const developmentSignIn = async () => { const r = await request('development-login', {}); if (!r.ok) throw Error(); const d = await r.json(); await setStoredValue(refreshKey, d.refresh_token); await storeUser(d.user) }
  const completeOnboarding = async (data: OnboardingData) => { const refreshToken = await getStoredValue(refreshKey); if (!refreshToken) throw Error('AUTH_REQUIRED'); const refreshed = await request('refresh', { refresh_token: refreshToken }); if (!refreshed.ok) { await removeStoredValue(refreshKey); await removeStoredValue(userKey); setUser(null); throw Error('AUTH_REQUIRED') }; const session = await refreshed.json(); await setStoredValue(refreshKey, session.refresh_token); const r = await fetch(`${apiBaseUrl}/api/v1/users/me/onboarding`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ ...data, preferred_language: user?.preferred_language ?? 'sk' }) }); if (!r.ok) throw Error('ONBOARDING_FAILED'); await storeUser(await r.json()) }
  const signOut = async () => { const token = await getStoredValue(refreshKey); if (token) await request('logout', { refresh_token: token }); await removeStoredValue(refreshKey); await removeStoredValue(userKey); setUser(null) }
  return <C.Provider value={{ user, loading, signIn, developmentSignIn, signOut, completeOnboarding }}>{children}</C.Provider> }
export const useAuth = () => useContext(C)
