-- Sport LevelGo schema: identity.sql
-- Managed by Alembic migration 0002. Add future changes as a new migration.

CREATE TABLE user_auth_identities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, provider varchar(30) NOT NULL, provider_subject varchar(255) NOT NULL, provider_email citext, provider_email_verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider, provider_subject), UNIQUE(user_id, provider), CHECK(provider='GOOGLE'));

CREATE TABLE user_profiles (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT, nickname citext NOT NULL UNIQUE, first_name varchar(100) NOT NULL, last_name varchar(100) NOT NULL, date_of_birth date, gender varchar(20) NOT NULL DEFAULT 'UNSPECIFIED', school_or_employer varchar(255), profile_image_url text, bio text, country_code char(2), city varchar(120), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(length(nickname) BETWEEN 3 AND 30), CHECK(nickname ~ '^[A-Za-z0-9_.-]+$'), CHECK(gender IN ('MALE','FEMALE','OTHER','UNSPECIFIED')), CHECK(date_of_birth IS NULL OR date_of_birth <= CURRENT_DATE));

CREATE TABLE user_privacy_settings (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, show_full_name boolean NOT NULL DEFAULT true, show_age boolean NOT NULL DEFAULT false, show_gender boolean NOT NULL DEFAULT false, show_school_or_employer boolean NOT NULL DEFAULT true, show_city boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE auth_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_family_id uuid NOT NULL, refresh_token_hash varchar(255) NOT NULL UNIQUE, device_id_hash varchar(255), device_name varchar(255), platform varchar(30), user_agent text, ip_address inet, last_used_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, rotated_at timestamptz, revoked_at timestamptz, revoke_reason varchar(100), created_at timestamptz NOT NULL DEFAULT now(), CHECK(expires_at > created_at));

CREATE TABLE auth_login_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, provider varchar(30) NOT NULL, provider_subject_hash varchar(255), success boolean NOT NULL, failure_reason varchar(100), ip_address inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
