-- Sport LevelGo schema: tournaments.sql
-- Managed by Alembic migration 0002. Add future changes as a new migration.

CREATE TABLE tournaments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, season_id uuid REFERENCES seasons(id) ON DELETE SET NULL, format_id uuid NOT NULL REFERENCES tournament_formats(id) ON DELETE RESTRICT, created_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, name varchar(180) NOT NULL, description text, participation_type varchar(20) NOT NULL CHECK(participation_type IN ('INDIVIDUAL','TEAM')), status varchar(30) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','REGISTRATION_OPEN','REGISTRATION_CLOSED','IN_PROGRESS','FINISHED','CANCELLED')), registration_starts_at timestamptz, registration_ends_at timestamptz, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, city varchar(120) NOT NULL, location_details text, currency char(3) NOT NULL DEFAULT 'EUR', registration_fee numeric(12,2) NOT NULL DEFAULT 0 CHECK(registration_fee>=0), license_fee numeric(12,2) NOT NULL DEFAULT 0 CHECK(license_fee>=0), is_public boolean NOT NULL DEFAULT true, results_locked_at timestamptz, finished_at timestamptz, cancelled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at>starts_at), CHECK(registration_starts_at IS NULL OR registration_ends_at IS NULL OR registration_ends_at>registration_starts_at), CHECK(registration_ends_at IS NULL OR registration_ends_at<=starts_at));

CREATE TABLE tournament_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE, name varchar(120) NOT NULL, min_age integer, max_age integer, gender_requirement varchar(20), max_entries integer, required_team_size integer, registration_fee_override numeric(12,2), license_fee_override numeric(12,2), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tournament_id,name), CHECK(min_age IS NULL OR min_age>=0), CHECK(max_age IS NULL OR max_age>=0), CHECK(max_age IS NULL OR min_age IS NULL OR max_age>=min_age), CHECK(max_entries IS NULL OR max_entries>0), CHECK(required_team_size IS NULL OR required_team_size>0), CHECK(gender_requirement IS NULL OR gender_requirement IN ('MALE','FEMALE','OTHER','ANY')), CHECK(registration_fee_override IS NULL OR registration_fee_override>=0), CHECK(license_fee_override IS NULL OR license_fee_override>=0));

CREATE TABLE tournament_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, category_id uuid NOT NULL REFERENCES tournament_categories(id) ON DELETE RESTRICT, entry_type varchar(20) NOT NULL CHECK(entry_type IN ('INDIVIDUAL','TEAM')), registration_status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK(registration_status IN ('PENDING','ACCEPTED','REJECTED','CANCELLED','REMOVED')), registered_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, accepted_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, accepted_at timestamptz, rejected_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, rejected_at timestamptz, rejection_reason text, removed_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, removed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE individual_tournament_entries (entry_id uuid PRIMARY KEY REFERENCES tournament_entries(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tournament_id,user_id));

CREATE TABLE team_tournament_entries (entry_id uuid PRIMARY KEY REFERENCES tournament_entries(id) ON DELETE CASCADE, persistent_team_id uuid REFERENCES teams(id) ON DELETE RESTRICT, owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, display_name varchar(150) NOT NULL, is_public_team boolean NOT NULL DEFAULT false, is_open_for_players boolean NOT NULL DEFAULT false, roster_locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK((is_public_team AND persistent_team_id IS NULL) OR (NOT is_public_team AND persistent_team_id IS NOT NULL)), CHECK(NOT is_open_for_players OR is_public_team));

CREATE TABLE tournament_entry_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, entry_id uuid NOT NULL REFERENCES team_tournament_entries(entry_id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, joined_at timestamptz NOT NULL DEFAULT now(), added_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, removed_at timestamptz, removed_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(entry_id,user_id));

CREATE TABLE tournament_rounds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, category_id uuid NOT NULL REFERENCES tournament_categories(id) ON DELETE RESTRICT, round_number integer NOT NULL, name varchar(120), stage_type varchar(30) NOT NULL CHECK(stage_type IN ('SWISS','GROUP','ELIMINATION')), status varchar(20) NOT NULL DEFAULT 'NOT_STARTED' CHECK(status IN ('NOT_STARTED','IN_PROGRESS','FINISHED')), started_at timestamptz, finished_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(category_id,round_number,stage_type), CHECK(round_number>0));

CREATE TABLE tournament_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, category_id uuid NOT NULL REFERENCES tournament_categories(id) ON DELETE RESTRICT, name varchar(50) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(category_id,name));

CREATE TABLE tournament_group_entries (group_id uuid NOT NULL REFERENCES tournament_groups(id) ON DELETE CASCADE, entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, seed integer, PRIMARY KEY(group_id,entry_id));

CREATE TABLE matches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, category_id uuid NOT NULL REFERENCES tournament_categories(id) ON DELETE RESTRICT, round_id uuid NOT NULL REFERENCES tournament_rounds(id) ON DELETE RESTRICT, group_id uuid REFERENCES tournament_groups(id) ON DELETE SET NULL, participant_a_entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, participant_b_entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, score_a integer, score_b integer, tournament_points_a numeric(8,2), tournament_points_b numeric(8,2), result_type varchar(30) NOT NULL DEFAULT 'NO_RESULT' CHECK(result_type IN ('PARTICIPANT_A_WIN','PARTICIPANT_B_WIN','DRAW','NO_RESULT')), winner_entry_id uuid REFERENCES tournament_entries(id) ON DELETE RESTRICT, status varchar(20) NOT NULL DEFAULT 'SCHEDULED' CHECK(status IN ('SCHEDULED','IN_PROGRESS','FINISHED','CANCELLED')), scheduled_at timestamptz, finished_at timestamptz, recorded_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(participant_a_entry_id<>participant_b_entry_id), CHECK(score_a IS NULL OR score_a>=0), CHECK(score_b IS NULL OR score_b>=0), CHECK(tournament_points_a IS NULL OR tournament_points_a>=0), CHECK(tournament_points_b IS NULL OR tournament_points_b>=0));

CREATE TABLE match_result_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), match_id uuid NOT NULL REFERENCES matches(id) ON DELETE RESTRICT, performed_by_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, old_score_a integer, old_score_b integer, new_score_a integer, new_score_b integer, old_result_type varchar(30), new_result_type varchar(30), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE tournament_final_standings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, category_id uuid NOT NULL REFERENCES tournament_categories(id) ON DELETE RESTRICT, entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, final_rank integer NOT NULL CHECK(final_rank>0), matches_played integer NOT NULL DEFAULT 0 CHECK(matches_played>=0), wins integer NOT NULL DEFAULT 0 CHECK(wins>=0), draws integer NOT NULL DEFAULT 0 CHECK(draws>=0), losses integer NOT NULL DEFAULT 0 CHECK(losses>=0), score_for integer NOT NULL DEFAULT 0, score_against integer NOT NULL DEFAULT 0, tournament_points numeric(10,2) NOT NULL DEFAULT 0, tie_break_data jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(category_id,entry_id), UNIQUE(category_id,final_rank));
