-- Sport LevelGo schema: xp.sql
-- Managed by Alembic migration 0002. Add future changes as a new migration.

CREATE TABLE player_sport_xp (user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, xp numeric(18,4) NOT NULL DEFAULT 0 CHECK(xp>=0), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,sport_id));

CREATE TABLE player_season_xp (user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT, xp numeric(18,4) NOT NULL DEFAULT 0 CHECK(xp>=0), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,season_id));

CREATE TABLE team_sport_xp (team_id uuid NOT NULL REFERENCES teams(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, xp numeric(18,4) NOT NULL DEFAULT 0 CHECK(xp>=0), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(team_id,sport_id));

CREATE TABLE team_season_xp (team_id uuid NOT NULL REFERENCES teams(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT, xp numeric(18,4) NOT NULL DEFAULT 0 CHECK(xp>=0), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(team_id,season_id));

CREATE TABLE player_xp_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, season_id uuid REFERENCES seasons(id) ON DELETE RESTRICT, tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, match_id uuid REFERENCES matches(id) ON DELETE RESTRICT, entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, xp_delta numeric(18,4) NOT NULL, all_time_xp_before numeric(18,4) NOT NULL, all_time_xp_after numeric(18,4) NOT NULL, season_xp_before numeric(18,4), season_xp_after numeric(18,4), reason_code varchar(50) NOT NULL, formula_version varchar(50) NOT NULL, calculation_data jsonb, idempotency_key varchar(120) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), CHECK(all_time_xp_after=all_time_xp_before+xp_delta));

CREATE TABLE team_xp_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), team_id uuid NOT NULL REFERENCES teams(id) ON DELETE RESTRICT, sport_id uuid NOT NULL REFERENCES sports(id) ON DELETE RESTRICT, season_id uuid REFERENCES seasons(id) ON DELETE RESTRICT, tournament_id uuid NOT NULL REFERENCES tournaments(id) ON DELETE RESTRICT, match_id uuid REFERENCES matches(id) ON DELETE RESTRICT, entry_id uuid NOT NULL REFERENCES tournament_entries(id) ON DELETE RESTRICT, xp_delta numeric(18,4) NOT NULL, all_time_xp_before numeric(18,4) NOT NULL, all_time_xp_after numeric(18,4) NOT NULL, season_xp_before numeric(18,4), season_xp_after numeric(18,4), reason_code varchar(50) NOT NULL, formula_version varchar(50) NOT NULL, calculation_data jsonb, idempotency_key varchar(120) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), CHECK(all_time_xp_after=all_time_xp_before+xp_delta));
